# Generated by Django 5.0.2 on 2025-05-12 11:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("pickup_latitude", models.FloatField(blank=True, null=True)),
                ("pickup_longitude", models.FloatField(blank=True, null=True)),
                ("dest_latitude", models.FloatField(blank=True, null=True)),
                ("dest_longitude", models.FloatField(blank=True, null=True)),
                ("load_description", models.TextField(blank=True, null=True)),
                (
                    "accepted_fare",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "NGN"),
                            ("KES", "KES"),
                            ("ZAR", "ZAR"),
                            ("GHS", "GHS"),
                        ],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1 ton Truck", "1 ton Truck"),
                            ("1.5 ton Truck", "1.5 ton Truck"),
                            ("2 ton Truck", "2 ton Truck"),
                            ("4 ton Truck", "4 ton Truck"),
                            ("Bakkie", "Bakkie"),
                            ("8 ton Truck", "8 ton Truck"),
                            ("Motorbike", "Motorbike"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pickup",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("picked up", "Picked up"),
                            ("arrived at pickup", "Arrived at pickup"),
                            ("arrived at destination", "Arrived at destination"),
                            ("in progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.driver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="authentication.driver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("driver", "user")},
            },
        ),
    ]
