# Generated by Django 5.0.2 on 2025-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("picked up", "Picked up"),
                    ("arrived at pickup", "Arrived at pickup"),
                    ("arrived at destination", "Arrived at destination"),
                    ("in progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
