# Generated by Django 5.0.2 on 2025-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_remove_driver_first_name_remove_driver_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MotorBike", "MotorBike"),
                    ("1 ton Truck", "1 ton Truck"),
                    ("1.5 ton Truck", "1.5 ton Truck"),
                    ("2 ton Truck", "2 ton Truck"),
                    ("4 ton Truck", "4 ton Truck"),
                    ("Bakkie", "Bakkie"),
                    ("Car", "car"),
                    ("8 ton Truck", "8 ton Truck"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
