# Generated by Django 5.0.2 on 2025-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_driver_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="physical_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="physical_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
