post http://localhost:8000/auth/signup/driver/
Content-Type: application/json

{
    "email": "fyidweb3lord@gmail.com",
    "phone_number": "+234 7049906335",
    "full_name": "Mojibola Olalekan",
    "password": "driver123"
}
