# Generated by Django 5.0.2 on 2025-05-12 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trip_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("South Africa", "ZA"),
                            ("Kenya", "KE"),
                            ("Ghana", "GH"),
                            ("Nigeria", "NG"),
                        ],
                        default="South Africa",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "NGN"),
                            ("KES", "KES"),
                            ("ZAR", "ZAR"),
                            ("GHS", "GHS"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flutterwave", "Flutterwave"),
                            ("paystack", "Paystack"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="authentication.driver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
                    ),
                    models.Index(
                        fields=["trip_id"], name="payments_pa_trip_id_dc8420_idx"
                    ),
                ],
            },
        ),
    ]
